[tool.poetry]
name = "sudoku"
version = "0.1.0"
description = ""
authors = ["babdus <babdusi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pynput = "^1.7.7"
pyglet = "^2.0.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
